sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: true

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - mvn clean package
  - docker build .

deploy:
  - docker push ${DOCKER_USERNAME}/spring-boot-angular

env:
  global:
    - secure: KecMyd8ua7Q/nNSWL7rdxRbrEpxI9KXHW4RlxSmkUhhkd/weGgXg9rhQOufrruPFQjD3c36ntACFc8XQCkwgG66by3qz6lu/WhFM3oN04SJudPrzfj4YjmhRv2FTdxzK6jfChhx/KEa4knYD2M3hj9rIGQwg5X1ktysdl7UWI9U=
    - secure: QztO5+aU7rwV9Ze3w2RP0e/azr27PHcQx8Lz6H3QltWuhu2tJju0kAButvlNpWkD3s8vXmkEZQBLwQfZq0Wmu/BbTA5ueYFfewbzOAi84Q8JhppTklfLrB0mjLJO0/NKMDtz+LPxt3Hl3Pj+5Bf3pwZjKHYc57+i9YnnEALF8Aw=
    - secure: HkaRcOzQWpMWPya1mT8P0CwBgMIIO5qaz/N97ZkkTYKQ3CJbQPJ6HIhmSTC1e2eWejAqKcy0GMXGJUP/IghycieMoAsu9eB0+0fe4zB2CgyRftCV/FescqlVm45Ebsgm9TjndJG7jjsPXdiw+BFiAB4GQrqyAPHf4gNzeUnVqg0=
    - secure: CvkPpIvi2T74hGtU4wuVoXm9sDaW9vS4Tj7i8a4CebQBoL1URwezrp3mbJQXgg/x2oXWbCtZMNGCLLoPqUp5I9O+OlRd4W3ye/wbLaSk9Wb9fEKXwTUR7zQjqWRJulrj8/L1TQQozKq43Cs1RW8MoxkaArSg0sqU14hVDSec1zA=
    - secure: b0iX/atnE86Thv47ODVbqVrD/TEtvWPpRXhSHc9/XZIsNis0F+4J+nVFH5vUh5vR7cy/DwLuRB477ihixuNxkI5JiOTLEND4yH4F+qoCqFnzjtTTKBcz6jvUQ7Kq0bTmADKf0ZsgLqVNG+SRRzgdmyKk1vJCUdAFx1UAhx/WLmQ=
