language: java

jdk:
  - oraclejdk8

install: true

script: "mvn deploy --settings .repo-settings.xml -B"

after_success:
  - curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/fabiojmendes/spring-boot-angular/trigger/7b4affb0-8797-4544-8d4e-76670c9b6e84/

env:
  global:
  - secure: KecMyd8ua7Q/nNSWL7rdxRbrEpxI9KXHW4RlxSmkUhhkd/weGgXg9rhQOufrruPFQjD3c36ntACFc8XQCkwgG66by3qz6lu/WhFM3oN04SJudPrzfj4YjmhRv2FTdxzK6jfChhx/KEa4knYD2M3hj9rIGQwg5X1ktysdl7UWI9U=
  - secure: QztO5+aU7rwV9Ze3w2RP0e/azr27PHcQx8Lz6H3QltWuhu2tJju0kAButvlNpWkD3s8vXmkEZQBLwQfZq0Wmu/BbTA5ueYFfewbzOAi84Q8JhppTklfLrB0mjLJO0/NKMDtz+LPxt3Hl3Pj+5Bf3pwZjKHYc57+i9YnnEALF8Aw=
