sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: true

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - mvn clean package
  - docker build .

deploy:
  - docker push ${DOCKER_USERNAME}/spring-boot-angular
