security:
  user:
    password: password

#endpoints:
#  shutdown:
#    enabled: true

application:
  buffer-size: 25600

logging:
  level:
    org.springframework.security: WARN

server:
  tomcat:
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for

info:
  build:
    artifact: "@artifactId@"
    name: "@name@"
    description: "@description@"
    version: "@version@"
    build: "@buildNumber@"

spring:
  datasource:
    url: jdbc:derby:target/db;create=true;logDevice=./target/db