security:
  user:
    password: password

#endpoints:
#  shutdown:
#    enabled: true

logging:
  level:
    org.springframework.security: WARN

server:
  tomcat:
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for

info:
  build:
    artifact: "@artifactId@"
    name: "@name@"
    description: "@description@"
    version: "@version@"
    build: "@buildNumber@"
